package reqtrace

import (
	"fmt"
	"sort"
	"strings"
)

// Problem is one traceability defect.
type Problem struct {
	// Kind is a short machine-readable category.
	Kind string
	// Where is the file:line the problem is anchored to.
	Where string
	// Message explains the problem and, where there is one, the fix.
	Message string
}

func (p Problem) String() string {
	if p.Where == "" {
		return fmt.Sprintf("%s: %s", p.Kind, p.Message)
	}
	return fmt.Sprintf("%s: %s: %s", p.Where, p.Kind, p.Message)
}

// Problem kinds.
const (
	ProblemDuplicateID    = "duplicate-requirement"
	ProblemUnknownRef     = "unknown-requirement"
	ProblemUncovered      = "requirement-without-test"
	ProblemUntagged       = "test-without-requirement"
	ProblemBadLink        = "broken-link"
	ProblemNoRequirements = "no-requirements-found"
)

// Validate returns every traceability defect in the model, in a stable order.
//
// All four checks are failures rather than warnings: a reference to a
// requirement that does not exist is a typo, a requirement nothing verifies is
// the gap this whole exercise exists to prevent, and a test claiming no
// requirement means either the test or the requirements are incomplete.
func Validate(m Model) []Problem {
	var problems []Problem

	index := m.RequirementIndex()
	coverage := m.Coverage()

	if len(m.Requirements) == 0 {
		problems = append(problems, Problem{
			Kind:    ProblemNoRequirements,
			Message: "no req or spec items were found — check the requirements directory",
		})
	}

	// Duplicate IDs. Two requirements with one ID make coverage meaningless.
	seen := make(map[string]Requirement)
	for _, r := range m.Requirements {
		if first, exists := seen[r.ID]; exists {
			problems = append(problems, Problem{
				Kind:    ProblemDuplicateID,
				Where:   location(r.File, r.Line),
				Message: fmt.Sprintf("%s is already defined at %s", r.ID, location(first.File, first.Line)),
			})
			continue
		}
		seen[r.ID] = r
	}

	// A :links: target that does not exist, e.g. a spec pointing at a renamed req.
	for _, r := range m.Requirements {
		for _, target := range r.Links {
			if _, ok := index[target]; !ok {
				problems = append(problems, Problem{
					Kind:    ProblemBadLink,
					Where:   location(r.File, r.Line),
					Message: fmt.Sprintf("%s links to %s, which is not defined", r.ID, target),
				})
			}
		}
	}

	// A test claiming a requirement that does not exist.
	for _, t := range m.Tests {
		for _, id := range t.Requirements {
			if _, ok := index[id]; !ok {
				problems = append(problems, Problem{
					Kind:    ProblemUnknownRef,
					Where:   location(t.File, t.Line),
					Message: fmt.Sprintf("%s claims %s, which is not defined in the requirements", t.Name, id),
				})
			}
		}
	}

	// A test that claims nothing.
	for _, t := range m.Tests {
		if len(t.Requirements) == 0 {
			problems = append(problems, Problem{
				Kind:    ProblemUntagged,
				Where:   location(t.File, t.Line),
				Message: untaggedHint(t),
			})
		}
	}

	// A requirement nothing verifies.
	for _, r := range m.Requirements {
		if r.Exempt() || len(coverage[r.ID]) > 0 {
			continue
		}
		problems = append(problems, Problem{
			Kind:  ProblemUncovered,
			Where: location(r.File, r.Line),
			Message: fmt.Sprintf("%s has no test — cover it, or tag it %q and say in the text how it is verified",
				r.ID, ExemptTag),
		})
	}

	sort.SliceStable(problems, func(i, j int) bool {
		if problems[i].Kind != problems[j].Kind {
			return problems[i].Kind < problems[j].Kind
		}
		return problems[i].Where < problems[j].Where
	})

	return problems
}

func untaggedHint(t TestCase) string {
	if t.Kind == KindRobot {
		return fmt.Sprintf("%q declares no requirement — add e.g. [Tags]    REQ_CLI_001", t.Name)
	}
	return fmt.Sprintf("%s declares no requirement — add a doc comment line, e.g. // Requirements: REQ_CLI_001", t.Name)
}

func location(file string, line int) string {
	if file == "" {
		return ""
	}
	return fmt.Sprintf("%s:%d", file, line)
}

// Render produces the generated traceability page.
//
// The page carries a sphinx-needs test item per test, linked to the requirements
// it verifies, plus needtables that render the matrix from those links. The
// tables are built by sphinx-needs from the links rather than written out here,
// so the matrix in the built documentation cannot disagree with them.
func Render(m Model) string {
	m.Sort()

	var b strings.Builder

	writeLines(&b,
		".. Generated by tools/reqtrace — do not edit.",
		"   Regenerate with \"make reqs\" after changing a requirement or a test annotation.",
		"",
		"Traceability Matrix",
		"===================",
		"",
		"Every requirement is verified by at least one automated test, and every test",
		"declares the requirements it covers. Both directions are checked by",
		"``make check``, which fails on a requirement without a test, a test without a",
		"requirement, and a reference to a requirement that does not exist.",
		"",
		"Coverage is declared where the test lives: a Go test declares it in a",
		"``// Requirements:`` doc comment, a Robot test in its ``[Tags]``. This page is",
		"generated from those declarations.",
		"",
	)

	writeSummary(&b, m)
	writeCoverage(&b, m)
	writeMatrix(&b)
	writeTestItems(&b, m)

	return b.String()
}

// writeLines writes each argument as its own line.
func writeLines(b *strings.Builder, lines ...string) {
	for _, line := range lines {
		b.WriteString(line)
		b.WriteString("\n")
	}
}

func writeSummary(b *strings.Builder, m Model) {
	coverage := m.Coverage()

	goTests, robotTests := 0, 0
	for _, t := range m.Tests {
		if t.Kind == KindRobot {
			robotTests++
		} else {
			goTests++
		}
	}

	type areaStat struct {
		requirements int
		exempt       int
		verifiedBy   int
	}
	stats := map[string]*areaStat{}
	var areas []string
	for _, r := range m.Requirements {
		area := r.Area()
		if area == "" {
			area = "(other)"
		}
		stat, ok := stats[area]
		if !ok {
			stat = &areaStat{}
			stats[area] = stat
			areas = append(areas, area)
		}
		stat.requirements++
		if r.Exempt() {
			stat.exempt++
		}
		stat.verifiedBy += len(coverage[r.ID])
	}
	sort.Strings(areas)

	writeLines(b,
		"Summary",
		"-------",
		"",
		fmt.Sprintf("%d requirement items, verified by %d Go tests and %d Robot tests.",
			len(m.Requirements), goTests, robotTests),
		"",
		".. list-table::",
		"   :header-rows: 1",
		"   :widths: 40 20 20 20",
		"",
		"   * - Area",
		"     - Items",
		"     - Test links",
		"     - Exempt",
	)

	for _, area := range areas {
		stat := stats[area]
		writeLines(b,
			fmt.Sprintf("   * - %s", area),
			fmt.Sprintf("     - %d", stat.requirements),
			fmt.Sprintf("     - %d", stat.verifiedBy),
			fmt.Sprintf("     - %d", stat.exempt),
		)
	}
	b.WriteString("\n")
}

// writeCoverage emits the requirement-to-test table by name. The needtable
// views below it are the sphinx-needs-native rendering, but their link columns
// can only show need IDs; this table is the one a person reads.
func writeCoverage(b *strings.Builder, m Model) {
	coverage := m.Coverage()

	writeLines(b,
		"Coverage by requirement",
		"-----------------------",
		"",
		".. list-table::",
		"   :header-rows: 1",
		"   :widths: 34 46 20",
		"",
		"   * - Requirement",
		"     - Verified by",
		"     - Status",
	)

	for _, r := range m.Requirements {
		tests := coverage[r.ID]

		var names []string
		for _, t := range tests {
			names = append(names, t.Title())
		}

		verified := strings.Join(names, ", ")
		switch {
		case verified != "":
		case r.Exempt():
			verified = "*exempt: see the requirement text*"
		default:
			verified = "**nothing**"
		}

		status := r.Status
		if status == "" {
			status = "—"
		}

		writeLines(b,
			fmt.Sprintf("   * - :need:`%s`", r.ID),
			fmt.Sprintf("     - %s", verified),
			fmt.Sprintf("     - %s", status),
		)
	}
	b.WriteString("\n")
}

func writeMatrix(b *strings.Builder) {
	writeLines(b,
		"Requirements and the tests that verify them",
		"-------------------------------------------",
		"",
		".. needtable::",
		"   :types: req",
		"   :columns: id;title;status;links_back",
		"   :style: table",
		"",
		"Specifications",
		"--------------",
		"",
		".. needtable::",
		"   :types: spec",
		"   :columns: id;title;status;links;links_back",
		"   :style: table",
		"",
		"Anything still uncovered",
		"------------------------",
		"",
		"This table is empty in a healthy build: ``make check`` fails before it is not,",
		"unless the item is deliberately exempt.",
		"",
		".. needtable::",
		"   :types: req;spec",
		"   :filter: not links_back",
		"   :columns: id;title;status;tags",
		"   :style: table",
		"",
	)
}

func writeTestItems(b *strings.Builder, m Model) {
	writeLines(b, "Test items", "----------", "")

	groups := []struct {
		kind    Kind
		heading string
		blurb   string
	}{
		{
			kind:    KindGo,
			heading: "Go unit tests",
			blurb:   "Run with ``make test``. No Docker required.",
		},
		{
			kind:    KindRobot,
			heading: "Robot Framework tests",
			blurb: "``test/cli.robot`` runs without Docker (``make test-cli``); the other suites " +
				"start the transform container (``make test-robot``).",
		},
	}

	for _, group := range groups {
		var tests []TestCase
		for _, t := range m.Tests {
			if t.Kind == group.kind {
				tests = append(tests, t)
			}
		}
		if len(tests) == 0 {
			continue
		}

		writeLines(b,
			group.heading,
			strings.Repeat("~", len(group.heading)),
			"",
			group.blurb,
			"",
		)

		for _, t := range tests {
			writeLines(b,
				fmt.Sprintf(".. test:: %s", t.Title()),
				fmt.Sprintf("    :id: %s", t.NeedID()),
			)
			if len(t.Requirements) > 0 {
				writeLines(b, fmt.Sprintf("    :links: %s", strings.Join(t.Requirements, ", ")))
			}
			writeLines(b,
				fmt.Sprintf("    :tags: %s", t.Kind),
				"",
				fmt.Sprintf("    ``%s:%d``", t.File, t.Line),
				"",
			)
		}
	}
}
